project: NeuralHamilton_v1.0_DeepONet
device: cuda:0
net: model.DeepONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89, 231, 928, 814, 269]
net_config:
  nodes: 128
  layers: 3
  branches: 10
optimizer_config:
  lr: 0.009467268535616663
scheduler_config:
  upper_bound: 350
  max_iter: 250
  infimum_lr: 3.915612189361335e-5
