project: NeuralHamilton_v1.0_DeepONet
device: cuda:0
net: model.DeepONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 50
batch_size: 100
seeds: [89, 231, 928, 814, 269]
net_config:
  nodes: 1024
  layers: 6
  branches: 50
optimizer_config:
  lr: 1.e-3 # Must contain dot for float
  betas: [0.85, 0.98]
scheduler_config:
  upper_bound: 250
  max_iter: 50
  infimum_lr: 1.e-5
