project: NeuralHamilton_v1.0_TraONet
device: cuda:0
net: model.TraONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89, 231, 928, 814, 269]
net_config:
  d_model: 64
  nhead: 4
  num_layers: 4
  dim_feedforward: 512
  dropout: 0.0
optimizer_config:
  lr: 0.0008483959427287777
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 4.958243978889227e-5
