project: NeuralHamilton_v1.0_VaRONet
device: cuda:1
net: model.VaRONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 50
batch_size: 100
seeds: [89, 231, 928, 814, 269]
net_config:
  hidden_size: 512
  num_layers: 4
  latent_size: 10
  dropout: 0.0
  kl_weight: 0.01
optimizer_config:
  lr: 1.e-3 # Must contain dot for float
  betas: [0.85, 0.98]
scheduler_config:
  upper_bound: 250
  max_iter: 50
  infimum_lr: 1.e-5
