study_name: TPE
trials: 100
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.TPESampler
  #kwargs:
  #  n_startup_trials: 10

#pruner:
#  name: pruner.PFLPruner
#  kwargs:
#    n_startup_trials: 10
#    n_warmup_epochs: 10
#    top_k: 10
#    target_epoch: 50

search_space:
  net_config:
    #layers:
    #  type: int
    #  min: 4
    #  max: 5
  optimizer_config:
    lr:
      type: float
      min: 3.e-1
      max: 8.e-1
      log: true
  scheduler_config:
    infimum_lr:
      type: float
      min: 1.e-7
      max: 1.e-3
      log: true
