study_name: TPEFullSearch
trials: 50
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.TPESampler
  #kwargs:
  #  n_startup_trials: 10

#pruner:
#  name: pruner.PFLPruner
#  kwargs:
#    n_startup_trials: 10
#    n_warmup_epochs: 10
#    top_k: 10
#    target_epoch: 50


search_space:
  optimizer_config:
    lr:
      type: float
      min: 5.e-3
      max: 1.e+0
      log: true
  scheduler_config:
    infimum_lr:
      type: float
      min: 1.e-7
      max: 5.e-3
      log: true
