study_name: TPEFullSearch
trials: 200
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.TPESampler
  #kwargs:
  #  n_startup_trials: 10

pruner:
  name: pruner.PFLPruner
  kwargs:
    n_startup_trials: 10
    n_warmup_epochs: 10
    top_k: 10
    target_epoch: 50


search_space:
  net_config:
    d_model:
      type: categorical
      choices: [16, 32, 64, 128]
    nhead:
      type: categorical
      choices: [4, 8, 16]
    num_layers:
      type: categorical
      choices: [2, 3, 4, 5]
    dim_feedforward:
      type: categorical
      choices: [256, 512, 1024]
  optimizer_config:
    lr:
      type: float
      min: 5.e-3
      max: 1.e-1
      log: true
  scheduler_config:
    upper_bound:
      type: int
      min: 300
      max: 400
      step: 50
    infimum_lr:
      type: float
      min: 1.e-7
      max: 5.e-3
      log: true
