project: NeuralHamilton_v1.26_TraONet
device: cuda:0
net: model.TraONet
#optimizer: torch.optim.adamw.AdamW
optimizer: splus.SPlus
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  d_model: 128
  nhead: 32
  num_layers: 4
  dim_feedforward: 1024
  dropout: 0.0
optimizer_config:
  lr: 0.08041067111196461
  eps: 1.e-10
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 0.00000080883803261902
