study_name: TPESearch
trials: 100
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.TPESampler
  #kwargs:
  #  n_startup_trials: 10

pruner:
  name: pruner.PFLPruner
  kwargs:
    n_startup_trials: 10
    n_warmup_epochs: 10
    top_k: 10
    target_epoch: 50

search_space:
  #net_config:
  #  nodes:
  #    type: categorical
  #    choices: [128, 256, 512, 1024]
  #  layers:
  #    type: categorical
  #    choices: [3, 4, 5, 6]
  #  branches:
  #    type: categorical
  #    choices: [10, 20, 30, 40]
  optimizer_config:
    lr:
      type: float
      min: 1.e-5
      max: 1.e-3
      log: true
  scheduler_config:
    upper_bound:
      type: int
      min: 300
      max: 400
      step: 50
    infimum_lr:
      type: float
      min: 1.e-8
      max: 1.e-5
      log: true
