project: NeuralHamilton_v1.11_DeepONet
device: cuda:0
net: model.DeepONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  nodes: 1024
  layers: 6
  branches: 32
optimizer_config:
  lr: 0.0009816787699537572
scheduler_config:
  upper_bound: 400
  max_iter: 250
  infimum_lr: 0.00000214112078057672
