project: NeuralHamilton_v1.18_DeepONet
device: cuda:0
net: model.DeepONet
#optimizer: torch.optim.adamw.AdamW
optimizer: soap.SOAP
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 50
batch_size: 100
seeds: [89, 231, 928]
net_config:
  nodes: 128
  layers: 3
  branches: 10
optimizer_config:
  lr: 1.e-2
scheduler_config:
  upper_bound: 300
  max_iter: 150
  infimum_lr: 1.e-5
