study_name: GridSearch
trials: 64
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.GridSampler
  #kwargs:
  #  n_startup_trials: 10

#pruner:
#  name: optuna.pruners.HyperbandPruner
#  kwargs:
#    min_resource: 10
#    max_resource: 100

search_space:
  net_config:
    nodes:
      type: categorical
      choices: [128, 256, 512, 1024]
    layers:
      type: categorical
      choices: [3, 4, 5, 6]
    branches:
      type: categorical
      choices: [10, 20, 30, 40]
  #optimizer_config:
  #  lr:
  #    type: float
  #    min: 1.e-3
  #    max: 1.e-2
  #    log: true
  #scheduler_config:
  #  T_max:
  #    type: int
  #    min: 10
  #    max: 100
  #  eta_min:
  #    type: float
  #    min: 1.e-6
  #    max: 1.e-4
  #    log: true
