project: NeuralHamilton_v1.12_DeepONet
device: cuda:0
net: model.DeepONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  nodes: 256
  layers: 5
  branches: 32
optimizer_config:
  lr: 0.0026796287072897336
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 0.00000321006670232738
