project: NeuralHamilton_v1.5_DeepONet
device: cuda:1
net: model.DeepONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  nodes: 512
  layers: 5
  branches: 32
optimizer_config:
  lr: 0.0014088923929828267
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 0.00000108482233910544
