project: NeuralHamilton_v1.3_DeepONet
device: cuda:1
net: model.DeepONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  nodes: 1024
  layers: 6
  branches: 50
optimizer_config:
  lr: 0.0006362177006307136
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 0.00000040296883414133 # Original
