project: NeuralHamilton_v1.18_DeepONet
device: cuda:0
net: model.DeepONet
#optimizer: torch.optim.adamw.AdamW
optimizer: soap.SOAP
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  nodes: 512
  layers: 6
  branches: 32
optimizer_config:
  lr: 0.003783421179168536
scheduler_config:
  upper_bound: 400
  max_iter: 250
  infimum_lr: 0.00000002485930916295
