project: NeuralHamilton_v1.16_MambONet
device: cuda:0
net: model.MambONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 50
batch_size: 100
seeds: [89, 231, 928]
net_config:
  d_model: 128
  num_layers1: 4
  n_head: 4
  num_layers2: 4
  d_ff: 1024
optimizer_config:
  lr: 1.e-3
scheduler_config:
  upper_bound: 300
  max_iter: 150
  infimum_lr: 1.e-6
