study_name: TPEFullSearch
trials: 100
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.TPESampler
  #kwargs:
  #  n_startup_trials: 10

pruner:
  name: pruner.PFLPrunerV2
  kwargs:
    n_startup_trials: 10
    n_warmup_epochs: 10
    top_k: 20
    target_epoch: 50

search_space:
  net_config:
    d_model:
      type: categorical
      choices: [128]
    num_layers1:
      type: categorical
      choices: [3, 4, 5]
    n_head:
      type: categorical
      choices: [4, 8, 16, 32]
    num_layers2:
      type: categorical
      choices: [3, 4, 5]
    d_ff:
      type: categorical
      choices: [1024]
  optimizer_config:
    lr:
      type: float
      min: 5.e-2
      max: 1.e+0
      log: true
  scheduler_config:
    upper_bound:
      type: int
      min: 300
      max: 400
      step: 50
    infimum_lr:
      type: float
      min: 1.e-7
      max: 5.e-2
      log: true
