project: NeuralHamilton_v1.3_MambONet
device: cuda:1
net: model.MambONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 500
batch_size: 100
seeds: [89]
net_config:
  d_model: 64
  num_layers1: 5
  n_head: 4
  num_layers2: 4
  d_ff: 1024
optimizer_config:
  lr: 0.00168647450418752
scheduler_config:
  upper_bound: 800
  max_iter: 500
  infimum_lr: 2.2745523885195647e-12 # 1:1
  #infimum_lr: 5.6203789874276416e-10 # 1:3
  #infimum_lr: 8.9565835673862984e-11 # 1:2
  #infimum_lr: 0.00000013887857726099 # Original
