study_name: GridSearch
trials: 81
seed: 42
metric: val_loss
direction: minimize

sampler:
  name: optuna.samplers.GridSampler
  #kwargs:
  #  n_startup_trials: 10

#pruner:
#  name: optuna.pruners.HyperbandPruner
#  kwargs:
#    min_resource: 10
#    max_resource: 100

search_space:
  net_config:
    d_model:
      type: categorical
      choices: [32, 64, 128]
    num_layers1:
      type: categorical
      choices: [2, 3, 4]
    num_layers2:
      type: categorical
      choices: [2, 3, 4]
    d_ff:
      type: categorical
      choices: [256, 512, 1024]
