project: NeuralHamilton_v1.12_MambONet
device: cuda:0
net: model.MambONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  #d_model: 256
  d_model: 128
  num_layers1: 5
  #n_head: 4
  n_head: 32
  #num_layers2: 5
  num_layers2: 4
  d_ff: 1024
optimizer_config:
  #lr: 0.00043933928880740834
  #lr: 0.000880787983483164
  lr: 0.000907903679684484
scheduler_config:
  #upper_bound: 300
  upper_bound: 300
  max_iter: 250
  #infimum_lr: 0.00000001950366474708
  infimum_lr: 0.00000010376147333445
  #infimum_lr: 1.e-8
