project: NeuralHamilton_v1.0_MambONet
device: cuda:1
net: model.MambONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 50
batch_size: 100
seeds: [89, 231, 928, 814, 269]
net_config:
  d_model: 128
  num_layers1: 4
  n_head: 4
  num_layers2: 4
  d_ff: 512
optimizer_config:
  lr: 1.e-3
scheduler_config:
  upper_bound: 300
  max_iter: 50
  infimum_lr: 1.e-6
