project: NeuralHamilton_v1.8_MambONet
device: cuda:0
net: model.MambONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  d_model: 128
  num_layers1: 6
  n_head: 16
  num_layers2: 4
  d_ff: 1024
optimizer_config:
  lr: 0.0009007121373486997
scheduler_config:
  upper_bound: 350
  max_iter: 250
  infimum_lr: 0.0000000199425412699 
