project: NeuralHamilton_v1.11_TraONet
device: cuda:0
net: model.TraONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  d_model: 128
  nhead: 16
  num_layers: 3
  dim_feedforward: 1024
  dropout: 0.0
optimizer_config:
  lr: 0.0003951061831534517
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 0.00000003653474822356
