project: NeuralHamilton_v1.2_TraONet
device: cuda:1
net: model.TraONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 50
batch_size: 100
seeds: [89, 231, 928]
net_config:
  d_model: 64
  nhead: 8
  num_layers: 3
  dim_feedforward: 512
  dropout: 0.0
optimizer_config:
  lr: 1.e-3
scheduler_config:
  upper_bound: 300
  max_iter: 50
  infimum_lr: 1.e-6
