project: NeuralHamilton_v1.1_TraONet
device: cuda:1
net: model.TraONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89, 231, 928, 814, 269]
net_config:
  d_model: 64
  nhead: 8
  num_layers: 3
  dim_feedforward: 512
  dropout: 0.0
optimizer_config:
  lr: 0.001464540033239398
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 3.711064639369724e-6
  #infimum_lr: 0.00004515855990776123
