project: NeuralHamilton_v1.12_TraONet
device: cuda:0
net: model.TraONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  #d_model: 128
  d_model: 64
  nhead: 4
  #num_layers: 3
  num_layers: 3
  #dim_feedforward: 1024
  dim_feedforward: 256
  dropout: 0.0
optimizer_config:
  #lr: 0.0003951061831534517
  lr: 0.002132779234059149
scheduler_config:
  upper_bound: 300
  max_iter: 250
  #infimum_lr: 0.00000003653474822356
  infimum_lr: 0.00000010045326935376
