project: NeuralHamilton_v1.2_TraONet
device: cuda:1
net: model.TraONet
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  d_model: 32
  nhead: 16
  num_layers: 4
  dim_feedforward: 512
  dropout: 0.0
optimizer_config:
  lr: 0.0015746255438489364
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 2.6068319068240619e-6 # 1:1
