project: NeuralHamilton_v1.21_TraONet_Probe
device: cuda:0
net: model.TraONet
#optimizer: torch.optim.adamw.AdamW
optimizer: splus.SPlus
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 10
batch_size: 100
seeds: [89]
net_config:
  d_model: 64
  nhead: 8
  num_layers: 3
  dim_feedforward: 512
  dropout: 0.0
optimizer_config:
  lr: 1.e-3
scheduler_config:
  upper_bound: 300
  max_iter: 150
  infimum_lr: 1.e-6
