project: NeuralHamilton_v1.21_TraONet
device: cuda:0
net: model.TraONet
#optimizer: torch.optim.adamw.AdamW
optimizer: splus.SPlus
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 250
batch_size: 100
seeds: [89]
net_config:
  d_model: 128
  nhead: 8
  num_layers: 3
  dim_feedforward: 1024
  dropout: 0.0
optimizer_config:
  lr: 0.044601492813681885
scheduler_config:
  upper_bound: 300
  max_iter: 250
  infimum_lr: 0.00002060335230487084
